### ISSUE TITLE
what's the addressable context

### ISSUE THREAD

**Issue by reqshark** [mafintosh/webcat#1]
can i do this locally? 

or should i be typing this into a publicly addressable server terminal on the internet?

**Comment by mafintosh** [comment]
it should work in both scenarios and even across the web since webrtc does hole punching!

**Comment by reqshark** [comment]
ok now it seems published on npm 

i was trying to ping you from ./bin.js before but now i'll try it from the normal webcat executable

**Comment by mafintosh** [comment]
there might be bugs - still early dev :)

**Comment by reqshark** [comment]
ya locally it's just hanging after i go

``` bash
$ webcat mafintosh
yo Mathias
```

the second line there is a fake next line thing terminal lets you do before last command completion.

iojs is still spinning

i'll try it on a server in new jersey and report back in a couple minutes

**Comment by reqshark** [comment]
osx loves it with the cool ninja stuff and boring ssl install but linux seems to be somewhat adverse to v1.7.1 and v1.6.2. 

what version of node are you using?

**Comment by mafintosh** [comment]
@reqshark found a bug in the lobby - let me fix it real quick

**Comment by max-mapper** [comment]
@reqshark im using iojs 1.6.4 and it compiled for me on mac os

**Comment by reqshark** [comment]
same here

**Comment by reqshark** [comment]
but are you getting my ping?

**Comment by reqshark** [comment]
``` bash
YO REQSHARK!
IM IN SEATTLE
dope
got
it
```

**Comment by max-mapper** [comment]
epic

**Comment by reqshark** [comment]
webcat #2

**Comment by mafintosh** [comment]
@reqshark upgrade to 1.1.1
