### ISSUE TITLE
Dependent version of ghsign is broken

### ISSUE THREAD

**Issue by watson** [mafintosh/webcat#10]
There is a bug in ghsign v2.0.0 which will be fixed when mafintosh/ghsign#7 is merged (hopefully). When a new version of ghsign is released it should be upgraded here.

Currently you'll get the error "ReferenceError: yourPrivateKey is not defined" when using webcat for the first time

**Comment by mafintosh** [comment]
fixed in 3.0.0 by reverting ghsign
